ESTA ES UNA API MUY RUDIMENTARIA. 

Carece de entorno gráfico o de todas esas cosas bonitas que atraen presupuesto. 

No funciona con botones sino con dolor. 

Sin embargo, es el punto de partida.

In [63]:
import pandas as pd
import requests

In [64]:

#input_data = input("Introduce path for data")
data = pd.read_csv("prueba.csv")

test = data["ModifiedDate"]
data = data.drop(["ModifiedDate"], axis=1)

data = data[["CompanyName", "SalesPerson"]]
data = pd.get_dummies(data, columns=["CompanyName", "SalesPerson"], drop_first=True)
data = data.reindex(columns=data.columns, fill_value=0)

In [65]:
Columns = ['CompanyName_A Cycle Shop',
 'CompanyName_A Great Bicycle Company',
 'CompanyName_A Typical Bike Shop',
 'CompanyName_Acceptable Sales & Service',
 'CompanyName_Action Bicycle Specialists',
 'CompanyName_Active Life Toys',
 'CompanyName_Active Systems',
 'CompanyName_Advanced Bike Components',
 'CompanyName_Aerobic Exercise Company',
 'CompanyName_Affordable Sports Equipment',
 'CompanyName_All Cycle Shop',
 'CompanyName_Alpine Ski House',
 'CompanyName_Alternative Vehicles',
 'CompanyName_Another Bicycle Company',
 'CompanyName_Another Sporting Goods Company',
 'CompanyName_Area Bike Accessories',
 'CompanyName_Area Sheet Metal Supply',
 'CompanyName_Associated Bikes',
 'CompanyName_Authentic Sales and Service',
 'CompanyName_Authorized Bike Sales and Rental',
 'CompanyName_Basic Bike Company',
 'CompanyName_Basic Sports Equipment',
 'CompanyName_Beneficial Exercises and Activities',
 "CompanyName_Best o' Bikes",
 'CompanyName_Bicycle Accessories and Kits',
 'CompanyName_Bicycle Lines Distributors',
 'CompanyName_Bicycle Merchandise Warehouse',
 'CompanyName_Big Cycle Mall',
 'CompanyName_Big-Time Bike Store',
 'CompanyName_Bike Dealers Association',
 'CompanyName_Bike Experts',
 'CompanyName_Bike Universe',
 'CompanyName_Bike World',
 'CompanyName_Bikes and Motorbikes',
 'CompanyName_Bikes for Kids and Adults',
 'CompanyName_Bikes for Two',
 'CompanyName_Black Bicycle Company',
 'CompanyName_Blue Bicycle Company',
 'CompanyName_Bold Bike Accessories',
 'CompanyName_Brakes and Gears',
 'CompanyName_Brightwork Company',
 'CompanyName_Bulk Discount Store',
 'CompanyName_Camping and Sports Store',
 'CompanyName_Capable Sales and Service',
 'CompanyName_Cash & Carry Bikes',
 'CompanyName_Catalog Store',
 'CompanyName_Center Cycle Shop',
 'CompanyName_Central Bicycle Specialists',
 'CompanyName_Central Discount Store',
 'CompanyName_Certified Bicycle Supply',
 'CompanyName_Certified Sports Supply',
 'CompanyName_Channel Outlet',
 'CompanyName_Chic Department Stores',
 'CompanyName_City Cycling',
 'CompanyName_City Manufacturing',
 'CompanyName_Citywide Service and Repair',
 'CompanyName_Client Discount Store',
 'CompanyName_Closeout Boutique',
 'CompanyName_Closest Bicycle Store',
 'CompanyName_Coalition Bike Company',
 'CompanyName_Coho Sports',
 'CompanyName_Commendable Bikes',
 'CompanyName_Commerce Bicycle Specialists',
 'CompanyName_Commuter Bicycle Store',
 'CompanyName_Consolidated Messenger',
 'CompanyName_Convenient Sales and Service',
 'CompanyName_Corner Bicycle Supply',
 'CompanyName_Countryside Company',
 'CompanyName_Courteous Bicycle Specialists',
 'CompanyName_Cross-Country Riding Supplies',
 'CompanyName_Curbside Sporting Goods',
 'CompanyName_Custom Accessories Company',
 'CompanyName_Custom Sales and Service',
 'CompanyName_Cycle Clearance',
 'CompanyName_Cycle Merchants',
 'CompanyName_Cycles Wholesaler & Mfg.',
 'CompanyName_Cycling Goods',
 'CompanyName_Demand Distributors',
 'CompanyName_Designated Distributors',
 'CompanyName_Designer Department Stores',
 'CompanyName_Discount Bicycle Specialists',
 'CompanyName_Discount Tours',
 'CompanyName_Distant Inn',
 'CompanyName_Distinctive Store',
 'CompanyName_District Mall',
 'CompanyName_Downhill Bicycle Specialists',
 'CompanyName_Downtown Hotel',
 'CompanyName_Eastside Department Store',
 'CompanyName_Eastside Parts Shop',
 'CompanyName_Economy Bikes Company',
 'CompanyName_Economy Center',
 'CompanyName_Efficient Cycling',
 'CompanyName_Eighth Bike Store',
 'CompanyName_Engineered Bike Systems',
 'CompanyName_Essential Bike Works',
 'CompanyName_Exceptional Cycle Services',
 'CompanyName_Exclusive Bicycle Mart',
 'CompanyName_Exercise Center',
 'CompanyName_Exertion Activities Club',
 'CompanyName_Exhibition Showroom',
 'CompanyName_Exhilarating Cycles',
 'CompanyName_Express Bike Services',
 'CompanyName_Extended Bike Sales',
 'CompanyName_Extended Tours',
 'CompanyName_Extraordinary Bike Works',
 'CompanyName_Extras Sporting Goods',
 'CompanyName_Extreme Riding Supplies',
 'CompanyName_Fabrikam Inc., West',
 'CompanyName_Fad Outlet',
 'CompanyName_Family Cycle Store',
 'CompanyName_Family Entertainment Center',
 "CompanyName_Family's Favorite Bike Shop",
 'CompanyName_Famous Bike Shop',
 'CompanyName_Farthermost Bike Shop',
 'CompanyName_Farthest Bike Store',
 'CompanyName_Fashionable Bikes and Accessories',
 'CompanyName_Fasteners & Bolts Outlet',
 'CompanyName_Field Trip Inc',
 'CompanyName_Field Trip Store',
 'CompanyName_Fifth Bike Store',
 'CompanyName_Finer Cycle Shop',
 'CompanyName_Finer Mart',
 'CompanyName_Finer Parts Shop',
 'CompanyName_Finer Riding Supplies',
 'CompanyName_Finish and Sealant Products',
 'CompanyName_First Bike Store',
 'CompanyName_First Cycle Store',
 'CompanyName_First Department Stores',
 'CompanyName_First-Rate Outlet',
 'CompanyName_Fitness Cycling',
 'CompanyName_Fitness Hotel',
 'CompanyName_Fitness Supplies',
 'CompanyName_Fitness Toy Store',
 'CompanyName_Flawless Bike Shop',
 'CompanyName_Fleet Bikes',
 'CompanyName_Friendly Bike Shop',
 'CompanyName_Friendly Neighborhood Bikes',
 'CompanyName_Front Sporting Goods',
 'CompanyName_Frugal Bike Shop',
 'CompanyName_Full-Service Bike Store',
 'CompanyName_Fun Times Club',
 'CompanyName_Fun Toys and Bikes',
 'CompanyName_Future Bikes',
 'CompanyName_Futuristic Bikes',
 'CompanyName_Futuristic Sport Distributors',
 'CompanyName_Gasless Cycle Shop',
 'CompanyName_General Bike Corporation',
 'CompanyName_General Cycle Storehouse',
 'CompanyName_General Department Stores',
 'CompanyName_General Industries',
 'CompanyName_General Riding Supplies',
 'CompanyName_General Supplies',
 'CompanyName_Genial Bike Associates',
 'CompanyName_Gift and Toy Store',
 'CompanyName_Global Sporting Goods',
 'CompanyName_Go-cart and Bike Specialists',
 'CompanyName_Golf and Cycle Store',
 'CompanyName_Good Bike Shop',
 'CompanyName_Good Toys',
 'CompanyName_Grand Bicycle Stores',
 'CompanyName_Grand Cycle Store',
 'CompanyName_Grand Industries',
 'CompanyName_Grand Sport Boutique',
 'CompanyName_Grease and Oil Products Company',
 'CompanyName_Great Bicycle Supply',
 'CompanyName_Greater Bike Store',
 'CompanyName_Handy Bike Services',
 'CompanyName_Hardware Components',
 'CompanyName_Health Spa, Limited',
 'CompanyName_Healthy Activity Store',
 'CompanyName_Highway Bike Shop',
 'CompanyName_Historic Bicycle Sales',
 'CompanyName_Home Town Bike Store',
 'CompanyName_Honest Repair Service',
 'CompanyName_Imaginary Toys',
 'CompanyName_Immense Manufacturing Company',
 'CompanyName_Imported and Domestic Cycles',
 'CompanyName_Impromptu Trips',
 'CompanyName_Initial Bike Company',
 'CompanyName_Instruments and Parts Company',
 'CompanyName_Journey Sporting Goods',
 'CompanyName_Kickstand Sellers',
 'CompanyName_Kickstands and Accessories Company',
 'CompanyName_Large Bike Shop',
 'CompanyName_Largest Bike Store',
 'CompanyName_Latest Accessories Sales',
 'CompanyName_Latest Sports Equipment',
 'CompanyName_Leading Sales & Repair',
 'CompanyName_Leather Seat Factory',
 'CompanyName_Leisure Activities',
 'CompanyName_Leisure Clearing House',
 'CompanyName_Little Bicycle Supply Shop',
 'CompanyName_Little Sports Center',
 'CompanyName_Local Hardware Factory',
 'CompanyName_Local Sales and Rental',
 'CompanyName_Locks Company',
 'CompanyName_Lots of Bikes Storehouse',
 'CompanyName_Low Price Cycles',
 'CompanyName_Machines & Cycles Store',
 'CompanyName_Mail Market',
 'CompanyName_Mail-Order Outlet',
 'CompanyName_Maintenance and Repair for Bicycles',
 'CompanyName_Major Cycling',
 'CompanyName_Major Sport Suppliers',
 'CompanyName_Major Sporting Goods',
 'CompanyName_Many Bikes Store',
 'CompanyName_Mechanical Products Ltd.',
 'CompanyName_Mercantile Outlet',
 'CompanyName_Metal Clearing House',
 'CompanyName_Metal Processing Company',
 'CompanyName_Metro Bike Works',
 'CompanyName_Metro Cycle Shop',
 'CompanyName_Metro Manufacturing',
 'CompanyName_Metro Metals Co.',
 'CompanyName_Metropolitan Bicycle Supply',
 'CompanyName_Metropolitan Manufacturing',
 'CompanyName_Metropolitan Sports Supply',
 'CompanyName_Moderately-Priced Bikes Store',
 'CompanyName_Modular Cycle Systems',
 'CompanyName_More Bikes!',
 'CompanyName_Mountain Bike Center',
 'CompanyName_Mountain Toy Store',
 'CompanyName_National Manufacturing',
 'CompanyName_Nearby Cycle Shop',
 'CompanyName_Nearby Sporting Goods',
 'CompanyName_Neighborhood Store',
 'CompanyName_Nice Bikes',
 'CompanyName_Non-Slip Pedal Company',
 'CompanyName_Nonskid Tire Company',
 'CompanyName_Novelty Bikes',
 'CompanyName_Number 1 Supply',
 'CompanyName_Number One Bike Co.',
 'CompanyName_Nuts and Bolts Mfg.',
 'CompanyName_Odometers and Accessories Company',
 'CompanyName_Official Parts Shop',
 'CompanyName_Oils and Fluids Warehouse',
 'CompanyName_One Bike Company',
 'CompanyName_Online Bike Sellers',
 'CompanyName_Online Bike Warehouse',
 'CompanyName_Operational Manufacturing',
 'CompanyName_Orange Bicycle Company',
 'CompanyName_Original Bicycle Supply Company',
 'CompanyName_Our Sporting Goods Store',
 'CompanyName_Out-of-the-Way Hotels',
 'CompanyName_Outdoor Aerobic Systems Company',
 'CompanyName_Outdoor Sporting Goods',
 'CompanyName_Outdoor Sports Supply',
 'CompanyName_Paint Supply',
 'CompanyName_Paints and Solvents Company',
 'CompanyName_Parcel Express Delivery Service',
 'CompanyName_Permanent Finish Products',
 'CompanyName_Petroleum Products Distributors',
 'CompanyName_Plastic Parts Company',
 'CompanyName_Practical Bike Supply Company',
 'CompanyName_Preferred Bikes',
 'CompanyName_Price-Cutter Discount Bikes',
 'CompanyName_Primary Bike Distributors',
 'CompanyName_Principal Bike Company',
 'CompanyName_Pro Sporting Goods',
 'CompanyName_Professional Containers and Packaging Co.',
 'CompanyName_Professional Cycle Store',
 'CompanyName_Professional Cyclists',
 'CompanyName_Professional Sales and Service',
 'CompanyName_Progressive Sports',
 'CompanyName_Prosperous Tours',
 'CompanyName_Purple Bicycle Company',
 'CompanyName_Quantity Discounts',
 'CompanyName_Quick Parts and Service',
 'CompanyName_Racing Bike Outlet',
 'CompanyName_Racing Partners',
 'CompanyName_Racing Toys',
 'CompanyName_Rally Master Company Inc',
 'CompanyName_Rampart Amusement Company',
 'CompanyName_Rapid Bikes',
 'CompanyName_Raw Materials Inc',
 'CompanyName_Real Sporting Goods',
 'CompanyName_Reasonable Bicycle Sales',
 'CompanyName_Recommended Bicycles',
 'CompanyName_Red Bicycle Company',
 'CompanyName_Refined Department Stores',
 'CompanyName_Regional Manufacturing',
 'CompanyName_Reliable Retail Center',
 'CompanyName_Remarkable Bike Store',
 'CompanyName_Remote Bicycle Specialists',
 'CompanyName_Rental Bikes',
 'CompanyName_Requisite Part Supply',
 'CompanyName_Resale Services',
 'CompanyName_Responsible Bike Dealers',
 'CompanyName_Retail Cycle Shop',
 'CompanyName_Retail Discount Store',
 'CompanyName_Retail Mall',
 'CompanyName_Retail Sporting Equipment',
 'CompanyName_Retail Sporting Goods',
 'CompanyName_Rewarding Activities Company',
 'CompanyName_Riders Company',
 'CompanyName_Riding Associates',
 'CompanyName_Riding Cycles',
 'CompanyName_Riding Excursions',
 'CompanyName_Road Way Sales and Rental',
 'CompanyName_Road-Way Mart',
 'CompanyName_Roadway Bike Emporium',
 'CompanyName_Roadway Supplies',
 'CompanyName_Roving Sports',
 'CompanyName_Rugged Bikes',
 'CompanyName_Running and Cycling Gear',
 'CompanyName_Rural Bicycle Supply',
 'CompanyName_Rural Cycle Emporium',
 'CompanyName_Rural Department Store',
 'CompanyName_Rural Sales and Service',
 'CompanyName_Safe Cycles Shop',
 'CompanyName_Safe Toys',
 'CompanyName_Sample Bike Store',
 'CompanyName_Satin Finish Company',
 'CompanyName_Scooters and Bikes Store',
 'CompanyName_Scratch-Resistant Finishes Company',
 'CompanyName_Seats and Saddles Company',
 'CompanyName_Security Racks and Locks Wholesalers',
 'CompanyName_Separate Parts Corporation',
 'CompanyName_Serious Cycles',
 'CompanyName_Sharp Bikes',
 'CompanyName_Sheet Metal Manufacturing',
 'CompanyName_Shipping Specialists',
 'CompanyName_Sixth Bike Store',
 'CompanyName_Sleek Bikes ',
 'CompanyName_Small Bike Shop',
 'CompanyName_Small Cycle Store',
 'CompanyName_Social Activities Club',
 'CompanyName_Solid Bike Parts',
 'CompanyName_Some Discount Store',
 'CompanyName_South Bike Company',
 'CompanyName_Sparkling Paint and Finishes',
 'CompanyName_Specialty Sports Store',
 'CompanyName_Sports Commodities',
 'CompanyName_Sports Merchandise',
 'CompanyName_Sports Products Store',
 'CompanyName_Sports Store',
 'CompanyName_Standard Bikes',
 'CompanyName_Stationary Bikes and Stands',
 'CompanyName_Strenuous Exercise Shop',
 'CompanyName_Sturdy Toys',
 'CompanyName_Suburban Cycle Shop',
 'CompanyName_Successful Sales Company',
 'CompanyName_Summer Sports Place',
 'CompanyName_Sundry Sporting Goods',
 'CompanyName_Superb Sales and Repair',
 'CompanyName_Superior Hardware Distributors',
 'CompanyName_Swift Cycles',
 'CompanyName_Synthetic Materials Manufacturing',
 'CompanyName_Systematic Sales',
 'CompanyName_Tachometers and Accessories',
 'CompanyName_Tandem Sales and Service',
 'CompanyName_Technical Parts Manufacturing',
 'CompanyName_Tenth Bike Store',
 'CompanyName_The Accessories Store',
 'CompanyName_The Bicycle Accessories Company',
 'CompanyName_The Bike Shop',
 'CompanyName_The Commissary',
 'CompanyName_The Gear Store',
 'CompanyName_The New Bike Store',
 'CompanyName_The Showroom',
 'CompanyName_Third Bike Store',
 'CompanyName_This Area Sporting Goods',
 'CompanyName_Thorough Parts and Repair Services',
 'CompanyName_Thrifty Parts and Sales',
 'CompanyName_Thrilling Bike Tours',
 'CompanyName_Timely Shipping Service',
 'CompanyName_Tire Exchange',
 'CompanyName_Tires and Tubes',
 'CompanyName_Top Bike Market',
 'CompanyName_Top Sports Supply',
 'CompanyName_Town Industries',
 'CompanyName_Traction Tire Company',
 'CompanyName_Trailblazing Sports',
 'CompanyName_Transport Bikes',
 'CompanyName_Transportation Options',
 'CompanyName_Travel Sports',
 'CompanyName_Travel Systems',
 'CompanyName_Trendy Department Stores',
 'CompanyName_Tubeless Tire Company',
 'CompanyName_Twelfth Bike Store',
 'CompanyName_Two Bike Shops',
 'CompanyName_Two-Seater Bikes',
 'CompanyName_Two-Wheeled Transit Company',
 'CompanyName_Unique Bikes',
 'CompanyName_Unsurpassed Bikes',
 'CompanyName_Urban Sports Emporium',
 'CompanyName_Utilitarian Sporting Goods',
 'CompanyName_Uttermost Bike Shop',
 'CompanyName_Vale Riding Supplies',
 'CompanyName_Valley Bicycle Distributors',
 'CompanyName_Valley Bicycle Specialists',
 'CompanyName_Valley Toy Store',
 'CompanyName_Variety Cycling',
 'CompanyName_Vast Bike Sales and Rental',
 'CompanyName_Vehicle Shop',
 'CompanyName_Vigorous Exercise Company',
 'CompanyName_Vigorous Sports Store',
 'CompanyName_Vintage Sport Boutique',
 'CompanyName_Vinyl and Plastic Goods Corporation',
 'CompanyName_Weekend Bike Tours',
 'CompanyName_West Side Mart',
 'CompanyName_Western Bike Supplies',
 'CompanyName_Westside Cycle Store',
 'CompanyName_Westside Plaza',
 'CompanyName_Wheel Gallery',
 'CompanyName_Wholesale Parts',
 'CompanyName_Wingtip Toys',
 'CompanyName_Wire Baskets and Parts',
 'CompanyName_Work and Play Association',
 'CompanyName_Workout Emporium',
 'CompanyName_World Bike Discount Store',
 'CompanyName_World of Bikes',
 'CompanyName_Year-Round Sports',
 'CompanyName_Yellow Bicycle Company',
 'SalesPerson_adventure-works\\garrett1',
 'SalesPerson_adventure-works\\jae0',
 'SalesPerson_adventure-works\\jillian0',
 'SalesPerson_adventure-works\\josé1',
 'SalesPerson_adventure-works\\linda3',
 'SalesPerson_adventure-works\\michael9',
 'SalesPerson_adventure-works\\pamela0',
 'SalesPerson_adventure-works\\shu0']

In [66]:
for column in Columns:
    if column not in data.columns:
        data[column] = [0] * len(data)
data_dict = data.to_dict()

C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)
C:\Users\engel\AppData\Local\Temp\ipykernel_2660\3889851535.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[column] = [0] * len(data)

In [67]:
import json

#Formateado para la API:
data_json = json.dumps({"data": [data_dict]})

suri = open("uri.json", "r")
scoring_uri = json.load(suri)["URI"]
suri.close()

   result  test
0      31    31
1     396   396
2      62    62
3     365   365
4     427   427
5     792   792
6     365   365
7     427   427
8      31    31
9     396   396

In [75]:
## La API per-sé:

headers = {"Content-Type": "application/json"}
response = requests.post(scoring_uri[0], data=data_json, headers=headers)

if response.status_code == 200:
  result = json.loads(response.json())
  df = pd.DataFrame({"result":result, "original": test})
  print(df)
  data["Exited"] = result
  display(data)
else:
  print(f"Error: {response.text}")

        result  original
0   792.000000        31
1   423.159457       396
2  1064.000000        62
3   841.811479       365
4  1016.076756       427
5   212.159457       792
6   539.741933       365
7   -98.258067       427
8   629.030879        31
9  -235.706734       396

,CompanyName_Advanced Bike Components,CompanyName_Aerobic Exercise Company,CompanyName_Associated Bikes,CompanyName_Bikes and Motorbikes,CompanyName_Metropolitan Sports Supply,CompanyName_Modular Cycle Systems,CompanyName_Progressive Sports,CompanyName_Rural Cycle Emporium,CompanyName_Sharp Bikes,SalesPerson_adventure-works\garrett1,...,CompanyName_Wire Baskets and Parts,CompanyName_Work and Play Association,CompanyName_Workout Emporium,CompanyName_World Bike Discount Store,CompanyName_World of Bikes,CompanyName_Year-Round Sports,CompanyName_Yellow Bicycle Company,SalesPerson_adventure-works\jae0,SalesPerson_adventure-works\michael9,Exited
0,False,False,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,792.000000
1,False,False,False,False,False,False,True,False,False,False,...,0,0,0,0,0,0,0,0,0,423.159457
2,True,False,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,1064.000000
3,False,False,False,False,False,True,False,False,False,False,...,0,0,0,0,0,0,0,0,0,841.811479
4,False,False,False,False,True,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,1016.076756
5,False,True,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,212.159457
6,False,False,True,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,539.741933
7,False,False,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,-98.258067
8,False,False,False,False,False,False,False,False,True,False,...,0,0,0,0,0,0,0,0,0,629.030879
9,False,False,False,True,False,False,False,False,False,True,...,0,0,0,0,0,0,0,0,0,-235.706734

# Local Run

In [69]:
data

,CompanyName_Advanced Bike Components,CompanyName_Aerobic Exercise Company,CompanyName_Associated Bikes,CompanyName_Bikes and Motorbikes,CompanyName_Metropolitan Sports Supply,CompanyName_Modular Cycle Systems,CompanyName_Progressive Sports,CompanyName_Rural Cycle Emporium,CompanyName_Sharp Bikes,SalesPerson_adventure-works\garrett1,...,CompanyName_Wire Baskets and Parts,CompanyName_Work and Play Association,CompanyName_Workout Emporium,CompanyName_World Bike Discount Store,CompanyName_World of Bikes,CompanyName_Year-Round Sports,CompanyName_Yellow Bicycle Company,SalesPerson_adventure-works\jae0,SalesPerson_adventure-works\michael9,Exited
0,False,False,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,792.000000
1,False,False,False,False,False,False,True,False,False,False,...,0,0,0,0,0,0,0,0,0,423.159457
2,True,False,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,1064.000000
3,False,False,False,False,False,True,False,False,False,False,...,0,0,0,0,0,0,0,0,0,841.811479
4,False,False,False,False,True,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,1016.076756
5,False,True,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,212.159457
6,False,False,True,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,539.741933
7,False,False,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,-98.258067
8,False,False,False,False,False,False,False,False,True,False,...,0,0,0,0,0,0,0,0,0,629.030879
9,False,False,False,True,False,False,False,False,False,True,...,0,0,0,0,0,0,0,0,0,-235.706734

In [70]:
import pickle

data_2  = json.loads(data_json)['data'][0]
data_2 = pd.DataFrame(data_2).to_numpy()

file_path = 'model.pkl'
with open(file_path, 'rb') as file:
    model = pickle.load(file)
result = model.predict(data_2).tolist()
result

c:\Users\engel\miniconda3\envs\azureStudy\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

[792.000000000001,
 423.15945707637957,
 1064.0,
 841.8114786084,
 1016.0767556662178,
 212.1594570763814,
 539.7419326473598,
 -98.25806735264848,
 629.0308794447601,
 -235.7067337689682]